/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as mainRouteRouteImport } from './routes/(main)/route'
import { Route as authRouteRouteImport } from './routes/(auth)/route'
import { Route as mainIndexRouteImport } from './routes/(main)/index'
import { Route as MediaKeyRouteImport } from './routes/media/$key'
import { Route as mainMusiciansRouteImport } from './routes/(main)/musicians'
import { Route as mainSettingsIndexRouteImport } from './routes/(main)/settings/index'
import { Route as mainMessagesIndexRouteImport } from './routes/(main)/messages/index'
import { Route as mainBandsIndexRouteImport } from './routes/(main)/bands/index'
import { Route as authSignUpIndexRouteImport } from './routes/(auth)/sign-up/index'
import { Route as authSignInIndexRouteImport } from './routes/(auth)/sign-in/index'
import { Route as mainUsersIdRouteImport } from './routes/(main)/users/$id'
import { Route as mainPostsPostIdRouteImport } from './routes/(main)/posts/$postId'
import { Route as mainBandsNewRouteImport } from './routes/(main)/bands/new'
import { Route as mainBandsIdRouteImport } from './routes/(main)/bands/$id'

const mainRouteRoute = mainRouteRouteImport.update({
  id: '/(main)',
  getParentRoute: () => rootRouteImport,
} as any)
const authRouteRoute = authRouteRouteImport.update({
  id: '/(auth)',
  getParentRoute: () => rootRouteImport,
} as any)
const mainIndexRoute = mainIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => mainRouteRoute,
} as any)
const MediaKeyRoute = MediaKeyRouteImport.update({
  id: '/media/$key',
  path: '/media/$key',
  getParentRoute: () => rootRouteImport,
} as any)
const mainMusiciansRoute = mainMusiciansRouteImport.update({
  id: '/musicians',
  path: '/musicians',
  getParentRoute: () => mainRouteRoute,
} as any)
const mainSettingsIndexRoute = mainSettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => mainRouteRoute,
} as any)
const mainMessagesIndexRoute = mainMessagesIndexRouteImport.update({
  id: '/messages/',
  path: '/messages/',
  getParentRoute: () => mainRouteRoute,
} as any)
const mainBandsIndexRoute = mainBandsIndexRouteImport.update({
  id: '/bands/',
  path: '/bands/',
  getParentRoute: () => mainRouteRoute,
} as any)
const authSignUpIndexRoute = authSignUpIndexRouteImport.update({
  id: '/sign-up/',
  path: '/sign-up/',
  getParentRoute: () => authRouteRoute,
} as any)
const authSignInIndexRoute = authSignInIndexRouteImport.update({
  id: '/sign-in/',
  path: '/sign-in/',
  getParentRoute: () => authRouteRoute,
} as any)
const mainUsersIdRoute = mainUsersIdRouteImport.update({
  id: '/users/$id',
  path: '/users/$id',
  getParentRoute: () => mainRouteRoute,
} as any)
const mainPostsPostIdRoute = mainPostsPostIdRouteImport.update({
  id: '/posts/$postId',
  path: '/posts/$postId',
  getParentRoute: () => mainRouteRoute,
} as any)
const mainBandsNewRoute = mainBandsNewRouteImport.update({
  id: '/bands/new',
  path: '/bands/new',
  getParentRoute: () => mainRouteRoute,
} as any)
const mainBandsIdRoute = mainBandsIdRouteImport.update({
  id: '/bands/$id',
  path: '/bands/$id',
  getParentRoute: () => mainRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/musicians': typeof mainMusiciansRoute
  '/media/$key': typeof MediaKeyRoute
  '/': typeof mainIndexRoute
  '/bands/$id': typeof mainBandsIdRoute
  '/bands/new': typeof mainBandsNewRoute
  '/posts/$postId': typeof mainPostsPostIdRoute
  '/users/$id': typeof mainUsersIdRoute
  '/sign-in': typeof authSignInIndexRoute
  '/sign-up': typeof authSignUpIndexRoute
  '/bands': typeof mainBandsIndexRoute
  '/messages': typeof mainMessagesIndexRoute
  '/settings': typeof mainSettingsIndexRoute
}
export interface FileRoutesByTo {
  '/musicians': typeof mainMusiciansRoute
  '/media/$key': typeof MediaKeyRoute
  '/': typeof mainIndexRoute
  '/bands/$id': typeof mainBandsIdRoute
  '/bands/new': typeof mainBandsNewRoute
  '/posts/$postId': typeof mainPostsPostIdRoute
  '/users/$id': typeof mainUsersIdRoute
  '/sign-in': typeof authSignInIndexRoute
  '/sign-up': typeof authSignUpIndexRoute
  '/bands': typeof mainBandsIndexRoute
  '/messages': typeof mainMessagesIndexRoute
  '/settings': typeof mainSettingsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(auth)': typeof authRouteRouteWithChildren
  '/(main)': typeof mainRouteRouteWithChildren
  '/(main)/musicians': typeof mainMusiciansRoute
  '/media/$key': typeof MediaKeyRoute
  '/(main)/': typeof mainIndexRoute
  '/(main)/bands/$id': typeof mainBandsIdRoute
  '/(main)/bands/new': typeof mainBandsNewRoute
  '/(main)/posts/$postId': typeof mainPostsPostIdRoute
  '/(main)/users/$id': typeof mainUsersIdRoute
  '/(auth)/sign-in/': typeof authSignInIndexRoute
  '/(auth)/sign-up/': typeof authSignUpIndexRoute
  '/(main)/bands/': typeof mainBandsIndexRoute
  '/(main)/messages/': typeof mainMessagesIndexRoute
  '/(main)/settings/': typeof mainSettingsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/musicians'
    | '/media/$key'
    | '/'
    | '/bands/$id'
    | '/bands/new'
    | '/posts/$postId'
    | '/users/$id'
    | '/sign-in'
    | '/sign-up'
    | '/bands'
    | '/messages'
    | '/settings'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/musicians'
    | '/media/$key'
    | '/'
    | '/bands/$id'
    | '/bands/new'
    | '/posts/$postId'
    | '/users/$id'
    | '/sign-in'
    | '/sign-up'
    | '/bands'
    | '/messages'
    | '/settings'
  id:
    | '__root__'
    | '/(auth)'
    | '/(main)'
    | '/(main)/musicians'
    | '/media/$key'
    | '/(main)/'
    | '/(main)/bands/$id'
    | '/(main)/bands/new'
    | '/(main)/posts/$postId'
    | '/(main)/users/$id'
    | '/(auth)/sign-in/'
    | '/(auth)/sign-up/'
    | '/(main)/bands/'
    | '/(main)/messages/'
    | '/(main)/settings/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  authRouteRoute: typeof authRouteRouteWithChildren
  mainRouteRoute: typeof mainRouteRouteWithChildren
  MediaKeyRoute: typeof MediaKeyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/(main)': {
      id: '/(main)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof mainRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)': {
      id: '/(auth)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof authRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(main)/': {
      id: '/(main)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof mainIndexRouteImport
      parentRoute: typeof mainRouteRoute
    }
    '/media/$key': {
      id: '/media/$key'
      path: '/media/$key'
      fullPath: '/media/$key'
      preLoaderRoute: typeof MediaKeyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(main)/musicians': {
      id: '/(main)/musicians'
      path: '/musicians'
      fullPath: '/musicians'
      preLoaderRoute: typeof mainMusiciansRouteImport
      parentRoute: typeof mainRouteRoute
    }
    '/(main)/settings/': {
      id: '/(main)/settings/'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof mainSettingsIndexRouteImport
      parentRoute: typeof mainRouteRoute
    }
    '/(main)/messages/': {
      id: '/(main)/messages/'
      path: '/messages'
      fullPath: '/messages'
      preLoaderRoute: typeof mainMessagesIndexRouteImport
      parentRoute: typeof mainRouteRoute
    }
    '/(main)/bands/': {
      id: '/(main)/bands/'
      path: '/bands'
      fullPath: '/bands'
      preLoaderRoute: typeof mainBandsIndexRouteImport
      parentRoute: typeof mainRouteRoute
    }
    '/(auth)/sign-up/': {
      id: '/(auth)/sign-up/'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof authSignUpIndexRouteImport
      parentRoute: typeof authRouteRoute
    }
    '/(auth)/sign-in/': {
      id: '/(auth)/sign-in/'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof authSignInIndexRouteImport
      parentRoute: typeof authRouteRoute
    }
    '/(main)/users/$id': {
      id: '/(main)/users/$id'
      path: '/users/$id'
      fullPath: '/users/$id'
      preLoaderRoute: typeof mainUsersIdRouteImport
      parentRoute: typeof mainRouteRoute
    }
    '/(main)/posts/$postId': {
      id: '/(main)/posts/$postId'
      path: '/posts/$postId'
      fullPath: '/posts/$postId'
      preLoaderRoute: typeof mainPostsPostIdRouteImport
      parentRoute: typeof mainRouteRoute
    }
    '/(main)/bands/new': {
      id: '/(main)/bands/new'
      path: '/bands/new'
      fullPath: '/bands/new'
      preLoaderRoute: typeof mainBandsNewRouteImport
      parentRoute: typeof mainRouteRoute
    }
    '/(main)/bands/$id': {
      id: '/(main)/bands/$id'
      path: '/bands/$id'
      fullPath: '/bands/$id'
      preLoaderRoute: typeof mainBandsIdRouteImport
      parentRoute: typeof mainRouteRoute
    }
  }
}

interface authRouteRouteChildren {
  authSignInIndexRoute: typeof authSignInIndexRoute
  authSignUpIndexRoute: typeof authSignUpIndexRoute
}

const authRouteRouteChildren: authRouteRouteChildren = {
  authSignInIndexRoute: authSignInIndexRoute,
  authSignUpIndexRoute: authSignUpIndexRoute,
}

const authRouteRouteWithChildren = authRouteRoute._addFileChildren(
  authRouteRouteChildren,
)

interface mainRouteRouteChildren {
  mainMusiciansRoute: typeof mainMusiciansRoute
  mainIndexRoute: typeof mainIndexRoute
  mainBandsIdRoute: typeof mainBandsIdRoute
  mainBandsNewRoute: typeof mainBandsNewRoute
  mainPostsPostIdRoute: typeof mainPostsPostIdRoute
  mainUsersIdRoute: typeof mainUsersIdRoute
  mainBandsIndexRoute: typeof mainBandsIndexRoute
  mainMessagesIndexRoute: typeof mainMessagesIndexRoute
  mainSettingsIndexRoute: typeof mainSettingsIndexRoute
}

const mainRouteRouteChildren: mainRouteRouteChildren = {
  mainMusiciansRoute: mainMusiciansRoute,
  mainIndexRoute: mainIndexRoute,
  mainBandsIdRoute: mainBandsIdRoute,
  mainBandsNewRoute: mainBandsNewRoute,
  mainPostsPostIdRoute: mainPostsPostIdRoute,
  mainUsersIdRoute: mainUsersIdRoute,
  mainBandsIndexRoute: mainBandsIndexRoute,
  mainMessagesIndexRoute: mainMessagesIndexRoute,
  mainSettingsIndexRoute: mainSettingsIndexRoute,
}

const mainRouteRouteWithChildren = mainRouteRoute._addFileChildren(
  mainRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  authRouteRoute: authRouteRouteWithChildren,
  mainRouteRoute: mainRouteRouteWithChildren,
  MediaKeyRoute: MediaKeyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
