/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as mainRouteRouteImport } from './routes/(main)/route'
import { Route as authRouteRouteImport } from './routes/(auth)/route'
import { Route as mainIndexRouteImport } from './routes/(main)/index'
import { Route as MediaSplatRouteImport } from './routes/media/$'
import { Route as mainMusiciansRouteImport } from './routes/(main)/musicians'
import { Route as mainSettingsIndexRouteImport } from './routes/(main)/settings/index'
import { Route as mainMessagesIndexRouteImport } from './routes/(main)/messages/index'
import { Route as mainBandsIndexRouteImport } from './routes/(main)/bands/index'
import { Route as authVerifyEmailIndexRouteImport } from './routes/(auth)/verify-email/index'
import { Route as authSignUpIndexRouteImport } from './routes/(auth)/sign-up/index'
import { Route as authSignInIndexRouteImport } from './routes/(auth)/sign-in/index'
import { Route as authResetPasswordIndexRouteImport } from './routes/(auth)/reset-password/index'
import { Route as authOnboardingIndexRouteImport } from './routes/(auth)/onboarding/index'
import { Route as authForgotPasswordIndexRouteImport } from './routes/(auth)/forgot-password/index'
import { Route as mainProfileUsernameRouteImport } from './routes/(main)/profile/$username'
import { Route as mainPostsPostIdRouteImport } from './routes/(main)/posts/$postId'
import { Route as mainDiscoverBandsRouteImport } from './routes/(main)/discover/bands'
import { Route as mainBandsSearchRouteImport } from './routes/(main)/bands/search'
import { Route as mainBandsNewRouteImport } from './routes/(main)/bands/new'

const mainRouteRoute = mainRouteRouteImport.update({
  id: '/(main)',
  getParentRoute: () => rootRouteImport,
} as any)
const authRouteRoute = authRouteRouteImport.update({
  id: '/(auth)',
  getParentRoute: () => rootRouteImport,
} as any)
const mainIndexRoute = mainIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => mainRouteRoute,
} as any)
const MediaSplatRoute = MediaSplatRouteImport.update({
  id: '/media/$',
  path: '/media/$',
  getParentRoute: () => rootRouteImport,
} as any)
const mainMusiciansRoute = mainMusiciansRouteImport.update({
  id: '/musicians',
  path: '/musicians',
  getParentRoute: () => mainRouteRoute,
} as any)
const mainSettingsIndexRoute = mainSettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => mainRouteRoute,
} as any)
const mainMessagesIndexRoute = mainMessagesIndexRouteImport.update({
  id: '/messages/',
  path: '/messages/',
  getParentRoute: () => mainRouteRoute,
} as any)
const mainBandsIndexRoute = mainBandsIndexRouteImport.update({
  id: '/bands/',
  path: '/bands/',
  getParentRoute: () => mainRouteRoute,
} as any)
const authVerifyEmailIndexRoute = authVerifyEmailIndexRouteImport.update({
  id: '/verify-email/',
  path: '/verify-email/',
  getParentRoute: () => authRouteRoute,
} as any)
const authSignUpIndexRoute = authSignUpIndexRouteImport.update({
  id: '/sign-up/',
  path: '/sign-up/',
  getParentRoute: () => authRouteRoute,
} as any)
const authSignInIndexRoute = authSignInIndexRouteImport.update({
  id: '/sign-in/',
  path: '/sign-in/',
  getParentRoute: () => authRouteRoute,
} as any)
const authResetPasswordIndexRoute = authResetPasswordIndexRouteImport.update({
  id: '/reset-password/',
  path: '/reset-password/',
  getParentRoute: () => authRouteRoute,
} as any)
const authOnboardingIndexRoute = authOnboardingIndexRouteImport.update({
  id: '/onboarding/',
  path: '/onboarding/',
  getParentRoute: () => authRouteRoute,
} as any)
const authForgotPasswordIndexRoute = authForgotPasswordIndexRouteImport.update({
  id: '/forgot-password/',
  path: '/forgot-password/',
  getParentRoute: () => authRouteRoute,
} as any)
const mainProfileUsernameRoute = mainProfileUsernameRouteImport.update({
  id: '/profile/$username',
  path: '/profile/$username',
  getParentRoute: () => mainRouteRoute,
} as any)
const mainPostsPostIdRoute = mainPostsPostIdRouteImport.update({
  id: '/posts/$postId',
  path: '/posts/$postId',
  getParentRoute: () => mainRouteRoute,
} as any)
const mainDiscoverBandsRoute = mainDiscoverBandsRouteImport.update({
  id: '/discover/bands',
  path: '/discover/bands',
  getParentRoute: () => mainRouteRoute,
} as any)
const mainBandsSearchRoute = mainBandsSearchRouteImport.update({
  id: '/bands/search',
  path: '/bands/search',
  getParentRoute: () => mainRouteRoute,
} as any)
const mainBandsNewRoute = mainBandsNewRouteImport.update({
  id: '/bands/new',
  path: '/bands/new',
  getParentRoute: () => mainRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/musicians': typeof mainMusiciansRoute
  '/media/$': typeof MediaSplatRoute
  '/': typeof mainIndexRoute
  '/bands/new': typeof mainBandsNewRoute
  '/bands/search': typeof mainBandsSearchRoute
  '/discover/bands': typeof mainDiscoverBandsRoute
  '/posts/$postId': typeof mainPostsPostIdRoute
  '/profile/$username': typeof mainProfileUsernameRoute
  '/forgot-password': typeof authForgotPasswordIndexRoute
  '/onboarding': typeof authOnboardingIndexRoute
  '/reset-password': typeof authResetPasswordIndexRoute
  '/sign-in': typeof authSignInIndexRoute
  '/sign-up': typeof authSignUpIndexRoute
  '/verify-email': typeof authVerifyEmailIndexRoute
  '/bands': typeof mainBandsIndexRoute
  '/messages': typeof mainMessagesIndexRoute
  '/settings': typeof mainSettingsIndexRoute
}
export interface FileRoutesByTo {
  '/musicians': typeof mainMusiciansRoute
  '/media/$': typeof MediaSplatRoute
  '/': typeof mainIndexRoute
  '/bands/new': typeof mainBandsNewRoute
  '/bands/search': typeof mainBandsSearchRoute
  '/discover/bands': typeof mainDiscoverBandsRoute
  '/posts/$postId': typeof mainPostsPostIdRoute
  '/profile/$username': typeof mainProfileUsernameRoute
  '/forgot-password': typeof authForgotPasswordIndexRoute
  '/onboarding': typeof authOnboardingIndexRoute
  '/reset-password': typeof authResetPasswordIndexRoute
  '/sign-in': typeof authSignInIndexRoute
  '/sign-up': typeof authSignUpIndexRoute
  '/verify-email': typeof authVerifyEmailIndexRoute
  '/bands': typeof mainBandsIndexRoute
  '/messages': typeof mainMessagesIndexRoute
  '/settings': typeof mainSettingsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(auth)': typeof authRouteRouteWithChildren
  '/(main)': typeof mainRouteRouteWithChildren
  '/(main)/musicians': typeof mainMusiciansRoute
  '/media/$': typeof MediaSplatRoute
  '/(main)/': typeof mainIndexRoute
  '/(main)/bands/new': typeof mainBandsNewRoute
  '/(main)/bands/search': typeof mainBandsSearchRoute
  '/(main)/discover/bands': typeof mainDiscoverBandsRoute
  '/(main)/posts/$postId': typeof mainPostsPostIdRoute
  '/(main)/profile/$username': typeof mainProfileUsernameRoute
  '/(auth)/forgot-password/': typeof authForgotPasswordIndexRoute
  '/(auth)/onboarding/': typeof authOnboardingIndexRoute
  '/(auth)/reset-password/': typeof authResetPasswordIndexRoute
  '/(auth)/sign-in/': typeof authSignInIndexRoute
  '/(auth)/sign-up/': typeof authSignUpIndexRoute
  '/(auth)/verify-email/': typeof authVerifyEmailIndexRoute
  '/(main)/bands/': typeof mainBandsIndexRoute
  '/(main)/messages/': typeof mainMessagesIndexRoute
  '/(main)/settings/': typeof mainSettingsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/musicians'
    | '/media/$'
    | '/'
    | '/bands/new'
    | '/bands/search'
    | '/discover/bands'
    | '/posts/$postId'
    | '/profile/$username'
    | '/forgot-password'
    | '/onboarding'
    | '/reset-password'
    | '/sign-in'
    | '/sign-up'
    | '/verify-email'
    | '/bands'
    | '/messages'
    | '/settings'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/musicians'
    | '/media/$'
    | '/'
    | '/bands/new'
    | '/bands/search'
    | '/discover/bands'
    | '/posts/$postId'
    | '/profile/$username'
    | '/forgot-password'
    | '/onboarding'
    | '/reset-password'
    | '/sign-in'
    | '/sign-up'
    | '/verify-email'
    | '/bands'
    | '/messages'
    | '/settings'
  id:
    | '__root__'
    | '/(auth)'
    | '/(main)'
    | '/(main)/musicians'
    | '/media/$'
    | '/(main)/'
    | '/(main)/bands/new'
    | '/(main)/bands/search'
    | '/(main)/discover/bands'
    | '/(main)/posts/$postId'
    | '/(main)/profile/$username'
    | '/(auth)/forgot-password/'
    | '/(auth)/onboarding/'
    | '/(auth)/reset-password/'
    | '/(auth)/sign-in/'
    | '/(auth)/sign-up/'
    | '/(auth)/verify-email/'
    | '/(main)/bands/'
    | '/(main)/messages/'
    | '/(main)/settings/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  authRouteRoute: typeof authRouteRouteWithChildren
  mainRouteRoute: typeof mainRouteRouteWithChildren
  MediaSplatRoute: typeof MediaSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/(main)': {
      id: '/(main)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof mainRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)': {
      id: '/(auth)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof authRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(main)/': {
      id: '/(main)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof mainIndexRouteImport
      parentRoute: typeof mainRouteRoute
    }
    '/media/$': {
      id: '/media/$'
      path: '/media/$'
      fullPath: '/media/$'
      preLoaderRoute: typeof MediaSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(main)/musicians': {
      id: '/(main)/musicians'
      path: '/musicians'
      fullPath: '/musicians'
      preLoaderRoute: typeof mainMusiciansRouteImport
      parentRoute: typeof mainRouteRoute
    }
    '/(main)/settings/': {
      id: '/(main)/settings/'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof mainSettingsIndexRouteImport
      parentRoute: typeof mainRouteRoute
    }
    '/(main)/messages/': {
      id: '/(main)/messages/'
      path: '/messages'
      fullPath: '/messages'
      preLoaderRoute: typeof mainMessagesIndexRouteImport
      parentRoute: typeof mainRouteRoute
    }
    '/(main)/bands/': {
      id: '/(main)/bands/'
      path: '/bands'
      fullPath: '/bands'
      preLoaderRoute: typeof mainBandsIndexRouteImport
      parentRoute: typeof mainRouteRoute
    }
    '/(auth)/verify-email/': {
      id: '/(auth)/verify-email/'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof authVerifyEmailIndexRouteImport
      parentRoute: typeof authRouteRoute
    }
    '/(auth)/sign-up/': {
      id: '/(auth)/sign-up/'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof authSignUpIndexRouteImport
      parentRoute: typeof authRouteRoute
    }
    '/(auth)/sign-in/': {
      id: '/(auth)/sign-in/'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof authSignInIndexRouteImport
      parentRoute: typeof authRouteRoute
    }
    '/(auth)/reset-password/': {
      id: '/(auth)/reset-password/'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof authResetPasswordIndexRouteImport
      parentRoute: typeof authRouteRoute
    }
    '/(auth)/onboarding/': {
      id: '/(auth)/onboarding/'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof authOnboardingIndexRouteImport
      parentRoute: typeof authRouteRoute
    }
    '/(auth)/forgot-password/': {
      id: '/(auth)/forgot-password/'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof authForgotPasswordIndexRouteImport
      parentRoute: typeof authRouteRoute
    }
    '/(main)/profile/$username': {
      id: '/(main)/profile/$username'
      path: '/profile/$username'
      fullPath: '/profile/$username'
      preLoaderRoute: typeof mainProfileUsernameRouteImport
      parentRoute: typeof mainRouteRoute
    }
    '/(main)/posts/$postId': {
      id: '/(main)/posts/$postId'
      path: '/posts/$postId'
      fullPath: '/posts/$postId'
      preLoaderRoute: typeof mainPostsPostIdRouteImport
      parentRoute: typeof mainRouteRoute
    }
    '/(main)/discover/bands': {
      id: '/(main)/discover/bands'
      path: '/discover/bands'
      fullPath: '/discover/bands'
      preLoaderRoute: typeof mainDiscoverBandsRouteImport
      parentRoute: typeof mainRouteRoute
    }
    '/(main)/bands/search': {
      id: '/(main)/bands/search'
      path: '/bands/search'
      fullPath: '/bands/search'
      preLoaderRoute: typeof mainBandsSearchRouteImport
      parentRoute: typeof mainRouteRoute
    }
    '/(main)/bands/new': {
      id: '/(main)/bands/new'
      path: '/bands/new'
      fullPath: '/bands/new'
      preLoaderRoute: typeof mainBandsNewRouteImport
      parentRoute: typeof mainRouteRoute
    }
  }
}

interface authRouteRouteChildren {
  authForgotPasswordIndexRoute: typeof authForgotPasswordIndexRoute
  authOnboardingIndexRoute: typeof authOnboardingIndexRoute
  authResetPasswordIndexRoute: typeof authResetPasswordIndexRoute
  authSignInIndexRoute: typeof authSignInIndexRoute
  authSignUpIndexRoute: typeof authSignUpIndexRoute
  authVerifyEmailIndexRoute: typeof authVerifyEmailIndexRoute
}

const authRouteRouteChildren: authRouteRouteChildren = {
  authForgotPasswordIndexRoute: authForgotPasswordIndexRoute,
  authOnboardingIndexRoute: authOnboardingIndexRoute,
  authResetPasswordIndexRoute: authResetPasswordIndexRoute,
  authSignInIndexRoute: authSignInIndexRoute,
  authSignUpIndexRoute: authSignUpIndexRoute,
  authVerifyEmailIndexRoute: authVerifyEmailIndexRoute,
}

const authRouteRouteWithChildren = authRouteRoute._addFileChildren(
  authRouteRouteChildren,
)

interface mainRouteRouteChildren {
  mainMusiciansRoute: typeof mainMusiciansRoute
  mainIndexRoute: typeof mainIndexRoute
  mainBandsNewRoute: typeof mainBandsNewRoute
  mainBandsSearchRoute: typeof mainBandsSearchRoute
  mainDiscoverBandsRoute: typeof mainDiscoverBandsRoute
  mainPostsPostIdRoute: typeof mainPostsPostIdRoute
  mainProfileUsernameRoute: typeof mainProfileUsernameRoute
  mainBandsIndexRoute: typeof mainBandsIndexRoute
  mainMessagesIndexRoute: typeof mainMessagesIndexRoute
  mainSettingsIndexRoute: typeof mainSettingsIndexRoute
}

const mainRouteRouteChildren: mainRouteRouteChildren = {
  mainMusiciansRoute: mainMusiciansRoute,
  mainIndexRoute: mainIndexRoute,
  mainBandsNewRoute: mainBandsNewRoute,
  mainBandsSearchRoute: mainBandsSearchRoute,
  mainDiscoverBandsRoute: mainDiscoverBandsRoute,
  mainPostsPostIdRoute: mainPostsPostIdRoute,
  mainProfileUsernameRoute: mainProfileUsernameRoute,
  mainBandsIndexRoute: mainBandsIndexRoute,
  mainMessagesIndexRoute: mainMessagesIndexRoute,
  mainSettingsIndexRoute: mainSettingsIndexRoute,
}

const mainRouteRouteWithChildren = mainRouteRoute._addFileChildren(
  mainRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  authRouteRoute: authRouteRouteWithChildren,
  mainRouteRoute: mainRouteRouteWithChildren,
  MediaSplatRoute: MediaSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
