version: '3.8'
services:
    postgres:
        image: postgres:latest
        container_name: postgres
        environment:
            DB_USER: '${DB_USER}'
            POSTGRES_PASSWORD: '${DB_PASSWORD}'
            DB_HOST: '${DB_HOST}'
            POSTGRES_DB: '${DB_NAME}'
        ports:
            - '5432:5432'
        volumes:
            - pgdata:/var/lib/postgresql/data
    server:
        container_name: server
        build:
            context: ../../
            dockerfile: src/backend/Dockerfile
        ports:
            - '${PORT}:${PORT}'
        env_file:
            - .env
        # depends_on:
        #     - postgres
volumes:
    pgdata:
