import type { Metadata } from 'next';
import './globals.css';
import Providers from '@/providers';
import { ClerkProvider } from '@clerk/nextjs';

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app'
};

export default function RootLayout({
    children
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <ClerkProvider>
            <html lang="en" suppressHydrationWarning>
                <body className="overflow-y-scroll">
                    <Providers>{children}</Providers>
                </body>
            </html>
        </ClerkProvider>
    );
}
