/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as mainRouteImport } from './routes/(main)/route'
import { Route as mainIndexImport } from './routes/(main)/index'
import { Route as mainSettingsIndexImport } from './routes/(main)/settings/index'
import { Route as mainNotificationsIndexImport } from './routes/(main)/notifications/index'
import { Route as mainMessagesIndexImport } from './routes/(main)/messages/index'
import { Route as authSignInIndexImport } from './routes/(auth)/sign-in/index'
import { Route as mainUserIdImport } from './routes/(main)/user/$id'

// Create/Update Routes

const mainRouteRoute = mainRouteImport.update({
  id: '/(main)',
  getParentRoute: () => rootRoute,
} as any)

const mainIndexRoute = mainIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => mainRouteRoute,
} as any)

const mainSettingsIndexRoute = mainSettingsIndexImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => mainRouteRoute,
} as any)

const mainNotificationsIndexRoute = mainNotificationsIndexImport.update({
  id: '/notifications/',
  path: '/notifications/',
  getParentRoute: () => mainRouteRoute,
} as any)

const mainMessagesIndexRoute = mainMessagesIndexImport.update({
  id: '/messages/',
  path: '/messages/',
  getParentRoute: () => mainRouteRoute,
} as any)

const authSignInIndexRoute = authSignInIndexImport.update({
  id: '/(auth)/sign-in/',
  path: '/sign-in/',
  getParentRoute: () => rootRoute,
} as any)

const mainUserIdRoute = mainUserIdImport.update({
  id: '/user/$id',
  path: '/user/$id',
  getParentRoute: () => mainRouteRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/(main)': {
      id: '/(main)'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof mainRouteImport
      parentRoute: typeof rootRoute
    }
    '/(main)/': {
      id: '/(main)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof mainIndexImport
      parentRoute: typeof mainRouteImport
    }
    '/(main)/user/$id': {
      id: '/(main)/user/$id'
      path: '/user/$id'
      fullPath: '/user/$id'
      preLoaderRoute: typeof mainUserIdImport
      parentRoute: typeof mainRouteImport
    }
    '/(auth)/sign-in/': {
      id: '/(auth)/sign-in/'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof authSignInIndexImport
      parentRoute: typeof rootRoute
    }
    '/(main)/messages/': {
      id: '/(main)/messages/'
      path: '/messages'
      fullPath: '/messages'
      preLoaderRoute: typeof mainMessagesIndexImport
      parentRoute: typeof mainRouteImport
    }
    '/(main)/notifications/': {
      id: '/(main)/notifications/'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof mainNotificationsIndexImport
      parentRoute: typeof mainRouteImport
    }
    '/(main)/settings/': {
      id: '/(main)/settings/'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof mainSettingsIndexImport
      parentRoute: typeof mainRouteImport
    }
  }
}

// Create and export the route tree

interface mainRouteRouteChildren {
  mainIndexRoute: typeof mainIndexRoute
  mainUserIdRoute: typeof mainUserIdRoute
  mainMessagesIndexRoute: typeof mainMessagesIndexRoute
  mainNotificationsIndexRoute: typeof mainNotificationsIndexRoute
  mainSettingsIndexRoute: typeof mainSettingsIndexRoute
}

const mainRouteRouteChildren: mainRouteRouteChildren = {
  mainIndexRoute: mainIndexRoute,
  mainUserIdRoute: mainUserIdRoute,
  mainMessagesIndexRoute: mainMessagesIndexRoute,
  mainNotificationsIndexRoute: mainNotificationsIndexRoute,
  mainSettingsIndexRoute: mainSettingsIndexRoute,
}

const mainRouteRouteWithChildren = mainRouteRoute._addFileChildren(
  mainRouteRouteChildren,
)

export interface FileRoutesByFullPath {
  '/': typeof mainIndexRoute
  '/user/$id': typeof mainUserIdRoute
  '/sign-in': typeof authSignInIndexRoute
  '/messages': typeof mainMessagesIndexRoute
  '/notifications': typeof mainNotificationsIndexRoute
  '/settings': typeof mainSettingsIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof mainIndexRoute
  '/user/$id': typeof mainUserIdRoute
  '/sign-in': typeof authSignInIndexRoute
  '/messages': typeof mainMessagesIndexRoute
  '/notifications': typeof mainNotificationsIndexRoute
  '/settings': typeof mainSettingsIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/(main)': typeof mainRouteRouteWithChildren
  '/(main)/': typeof mainIndexRoute
  '/(main)/user/$id': typeof mainUserIdRoute
  '/(auth)/sign-in/': typeof authSignInIndexRoute
  '/(main)/messages/': typeof mainMessagesIndexRoute
  '/(main)/notifications/': typeof mainNotificationsIndexRoute
  '/(main)/settings/': typeof mainSettingsIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/user/$id'
    | '/sign-in'
    | '/messages'
    | '/notifications'
    | '/settings'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/user/$id'
    | '/sign-in'
    | '/messages'
    | '/notifications'
    | '/settings'
  id:
    | '__root__'
    | '/(main)'
    | '/(main)/'
    | '/(main)/user/$id'
    | '/(auth)/sign-in/'
    | '/(main)/messages/'
    | '/(main)/notifications/'
    | '/(main)/settings/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  mainRouteRoute: typeof mainRouteRouteWithChildren
  authSignInIndexRoute: typeof authSignInIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  mainRouteRoute: mainRouteRouteWithChildren,
  authSignInIndexRoute: authSignInIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/(main)",
        "/(auth)/sign-in/"
      ]
    },
    "/(main)": {
      "filePath": "(main)/route.tsx",
      "children": [
        "/(main)/",
        "/(main)/user/$id",
        "/(main)/messages/",
        "/(main)/notifications/",
        "/(main)/settings/"
      ]
    },
    "/(main)/": {
      "filePath": "(main)/index.tsx",
      "parent": "/(main)"
    },
    "/(main)/user/$id": {
      "filePath": "(main)/user/$id.tsx",
      "parent": "/(main)"
    },
    "/(auth)/sign-in/": {
      "filePath": "(auth)/sign-in/index.tsx"
    },
    "/(main)/messages/": {
      "filePath": "(main)/messages/index.tsx",
      "parent": "/(main)"
    },
    "/(main)/notifications/": {
      "filePath": "(main)/notifications/index.tsx",
      "parent": "/(main)"
    },
    "/(main)/settings/": {
      "filePath": "(main)/settings/index.tsx",
      "parent": "/(main)"
    }
  }
}
ROUTE_MANIFEST_END */
